SELECT top 100 base_date as date,
	   base_date as fod,
       us_date [mmddyyyy], 
       iso_date [yyyymmdd],
	   [year_month] as yyyymm,
       base_date_end as eod, 
       base_year as year, 
       base_month as month, 
       base_month_2_digit as mm, 
       base_month_name, 
       base_month_name_short as monthname, 
       iso_week, 
       base_day as day, 
       base_day_2_digit as dd, 
       day_of_week, 
       fiscal_year, 
       fiscal_quarter, 
       fy_quarter, 
       start_of_week, 
       end_of_week, 
       start_of_month, 
       end_of_month, 
       first_of_year, 
       end_of_year, 
       first_of_fiscal, 
       end_of_fiscal, 
       first_of_q1, 
       end_of_q1, 
       first_of_q2, 
       end_of_q2, 
       first_of_q3, 
       end_of_q3, 
       first_of_q4, 
       end_of_q4, 
       first_of_previous_month, 
       end_of_previous_month, 
       first_of_previous_year, 
       first_of_prev_6_months, 
       first_of_prev_3_months, 
       first_of_prev_2_months
FROM date_reference;